[package]
name = "bm_storage"
version = "2.0.0"
edition = "2024"

[dependencies]
bm_core = { path = "../core" }
rusqlite = "0.33"

[target.'cfg(windows)'.dependencies]
rusqlite = { version = "0.33", features = ["bundled"] }
